# Generated by Django 4.1 on 2022-09-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=' ', max_length=500)),
                ('details', models.CharField(default=' ', max_length=1000)),
                ('link', models.CharField(default=' ', max_length=200)),
            ],
        ),
    ]
